test stage

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -74,6 +74,41 @@ jobs:
             echo "Test is failed!!!"
             exit 1
           fi
+
+  Docker-Build:
+    needs: unit-testing
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out Git repository
+        uses: actions/checkout@v4
+
+      - name: Download build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: tic-tac-artifact
+          path: dist/
+      
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ vars.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: build image and push
+        run: |
+         docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ github.sha }} .
+         docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ github.sha }}
+         if [ $? -eq 0 ]; then
+            echo "image pushed successfully!!"
+          else 
+            echo "build and push docker image step failed!!!"
+            exit 1
+          fi
+
+
              
       
 
